AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Local test
Resources:
  SamLocalstackTemplate:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Environment:
        Variables:
          NODE_ENV: !Ref NODE_ENV
      Events:
        ApiGet:
          Type: Api
          Properties:
            Path: /resource/{resourceId}
            Method: get